sudo: false
language: python
cache: pip

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.5
          env: TOXENV=qa

install: pip install --ignore-installed --upgrade setuptools pip tox
script: tox -vv
